version: '3'
services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 3316:3306
  app:
    build:
      context: .
    container_name: app
    ports:
      - 80:7878
    volumes:
      - ./:/app
    depends_on:
      - mysql

volumes:
  db-volume:
